import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
    title: "Výčetka | Max Juškevič",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className="dark">
        <Header/>
        <div className="xl:p-20">
            {children}
        </div>
        <Footer/>
        </body>
        </html>
    );
}
