import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import Footer from "@/components/footer";
import DynamicHeader from "@/components/DynamicHeader";
import {Toaster} from "@/components/ui/toaster";

export const metadata: Metadata = {
    title: "Výčetka | Max Juškevič",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className="dark">
        <DynamicHeader/>
        <div className="xl:p-20">
            {children}
        </div>
        <Footer/>
        <Toaster/>
        </body>
        </html>
    );
}
